class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    #@submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # Home submission for students
  def submit_homework
    @user = User.find_by(session[:user_id])
    @course = Course.find_by(params[:course_id])
    @homework = Homework.find_by(params[:homework_id])


  end

  # POST /submissions
  # POST /submissions.json

  def mkdir(directory)
    token = directory.split('/')
    1.upto(token.size)  do |n|
      dir = token[0...n].join('/')
      #puts '***************************************************'
      #puts dir
      Dir.mkdir(dir) unless Dir.exist? (dir)
    end
  end

  def create
    @user = User.find_by(session[:user_id])
    @course = Course.find_by(params[:course_id])
    @homework = Homework.find_by(params[:homework_id])

    current_time = Time.new
    time = current_time.strftime('%Y_%m_%d-%H_%M_%S')
    file_type = params[:file].original_filename.partition('.')[-1]
    file_name = time + '.' + file_type

    directory = './UPLOAD/' + @course.course_name + '/' + @homework.hw_name + '/' + @user.user_login_name
    path_file = File.join(directory, file_name)

    mkdir(directory)


    puts '***************************************************'
    puts path_file
    abs_path = File.expand_path(File.dirname(path_file))
    abs_path_file = File.join(abs_path, file_name)
    puts '***************************************************'
    puts abs_path_file


    File.open(path_file, "w") { |f| f.write(params[:file].read.force_encoding('UTF-8')) }

    @submission = Submission.new
    @submission[:homework_id] = params[:homework_id]
    @submission[:user_id] = session[:user_id]
    @submission[:course_id] = params[:course_id]

    #=======================================================
    #Submission grade to be generated by compiler API
    #=======================================================

    @submission[:sm_grade] = -1

    @submission[:sm_src_dir] = path_file

    @submission.save

    redirect_to "/show_student"
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_submission
    @submission = Submission.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def submission_params
    params.require(:submission).permit(:homework_id, :user_id, :course_id, :sm_grade, :sm_time, :sm_src_dir)
  end
end
